// react-default/src/pages/CreateWord.jsx
import axios from 'axios';
import { useRef, useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import LoadingSpinner from '../components/LoadingSpinner';

import '../styles/CreateWord.scoped.css';

export default function CreateWord() {
  const [isLoading, setIsLoading] = useState(false);
  const [days, setData] = useState([]);
  const [day, setDay] = useState(1);

  const url = `http://localhost:5000`;

  const navigate = useNavigate();

  const getDays = useCallback(async () => {
    setIsLoading(true);
    axios.get(`${url}/days`).then((res) => {
      if (res.data.length === 0) {
        alert('등록된 날짜가 없습니다.');
        navigate(`/createDay`);
      } else {
        setData(res.data);
        setDay(res.data.length);
        setIsLoading(false);
      }
    });
  }, [url, navigate]);

  useEffect(() => {
    getDays();
  }, [getDays]);

  function onChange(e) {
    e.preventDefault();

    dayRef.current.value = e.target.value;
    setDay(e.target.value);
  }

  function createWord(e) {
    e.preventDefault();

    if (!isLoading) {
      const word = {
        day: dayRef.current.value,
        eng: engRef.current.value.trim(),
        kor: korRef.current.value.trim(),
        isComplete: false,
      };

      if (word.eng === '' || word.kor === '') {
        alert('단어를 입력해주세요.');
      } else {
        setIsLoading(true);
        axios.post(`${url}/words`, word).then((res) => {
          if (res.status === 201) {
            alert('단어가 추가되었습니다.');
            setIsLoading(false);
            navigate(`/wordList/${word.day}`);
          }
        });
      }
    }
  }

  const engRef = useRef(null);
  const korRef = useRef(null);
  const dayRef = useRef(null);

  if (isLoading) {
    return <LoadingSpinner />;
  }

  return (
    <form onSubmit={createWord}>
      <div className="inputWrap">
        <label htmlFor="eng">Eng</label>
        <input type="text" id="eng" placeholder="English" ref={engRef} />
      </div>
      <div className="inputWrap">
        <label htmlFor="kor">Kor</label>
        <input type="text" id="kor" placeholder="영어" ref={korRef} />
      </div>
      <div className="inputWrap">
        <label htmlFor="day">Day</label>
        <select id="day" ref={dayRef} value={day} onChange={onChange}>
          {days.map((day) => (
            <option key={day.id} value={day.day}>
              {day.day}
            </option>
          ))}
        </select>
      </div>
      <div className="inputWrap">
        <button
          type="submit"
          className={'btnCreate' + (isLoading ? 'disabled' : '')}
        >
          단어 추가
        </button>
      </div>
    </form>
  );
}

// vue3-composition/src/views/CreateWord.vue
<template>
  <LoadingSpinner v-if="isLoading" />

  <form v-else @submit.prevent>
    <div class="inputWrap">
      <label for="eng">Eng</label>
      <input type="text" id="eng" placeholder="Moon" v-model="eng" />
    </div>
    <div class="inputWrap">
      <label for="kor">Kor</label>
      <input type="text" id="kor" placeholder="달" v-model="kor" />
    </div>
    <div class="inputWrap">
      <label for="dayCount">Day</label>
      <select id="dayCount" v-model="day">
        <option v-for="item in days" :key="item.day" :value="item.day">
          {{ item.day }}
        </option>
      </select>
    </div>
    <div class="inputWrap">
      <button type="button" class="btnCreate" @click="createWord">
        단어 추가
      </button>
    </div>
  </form>
</template>

<script>
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { useApiStore } from '@/stores/api';
import axios from 'axios';

import LoadingSpinner from '@/components/LoadingSpinner.vue';

export default {
  components: {
    LoadingSpinner,
  },
  setup() {
    const isLoading = ref(true);
    const router = useRouter();
    const url = useApiStore();
    const days = ref([]);

    axios.get(`${url.api}/days`).then((res) => {
      isLoading.value = true;
      if (res.status === 200) {
        if (res.data.length === 0) {
          alert('등록된 날짜가 없습니다.');
          router.push({ path: `/createDay` });
        } else {
          days.value = res.data;
          day.value = days.value[days.value.length - 1].day;
          isLoading.value = false;
        }
      }
    });

    const word = ref({});
    const eng = ref('');
    const kor = ref('');
    const day = ref(1);

    const createWord = () => {
      word.value = {
        day: day.value,
        eng: eng.value.trim(),
        kor: kor.value.trim(),
        isComplete: false,
      };

      if (word.value.eng === '' || word.value.kor === '') {
        alert('단어를 입력해주세요.');
      } else {
        isLoading.value = true;
        axios.post(`${url.api}/words`, word.value).then((res) => {
          if (res.status === 201) {
            alert('단어가 추가되었습니다.');
            isLoading.value = false;
            router.push({ path: `/wordList/${day.value}` });
          }
        });
      }
    };

    return { isLoading, days, word, eng, kor, day, createWord };
  },
};
</script>

<style scoped>
.inputWrap {
  padding: 15px 0;
  font-size: 0;
}

.inputWrap label {
  display: inline-block;
  width: 80px;
  font-size: 20px;
  line-height: 40px;
  vertical-align: top;
  border-bottom: 2px solid #d9d9d9;
}

.inputWrap input,
.inputWrap select {
  width: 400px;
  height: 40px;
  font-size: 20px;
  line-height: 40px;
  padding: 0 30px;
  border: none;
  border-bottom: 2px solid #d9d9d9;
  outline: none;
  box-sizing: content-box;
}

.inputWrap input:focus {
  border-bottom: 2px solid #353535;
}
</style>
