// react-ts/src/pages/DayList.tsx
import axios from 'axios';
import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import LoadingSpinner from '../components/LoadingSpinner';

import '../styles/DayList.scoped.css';

export default function DayList() {
  const [isLoading, setIsLoading] = useState(false);
  const [days, setData] = useState([]);
  const url = `http://localhost:5000`;

  const getDays = useCallback(async () => {
    setIsLoading(true);
    axios.get(`${url}/days`).then((res) => {
      setData(res.data);
      setIsLoading(false);
    });
  }, [url]);

  useEffect(() => {
    getDays();
  }, [getDays]);

  if (isLoading) {
    return <LoadingSpinner />;
  }

  return (
    <ul className="days" id="days">
      {days.map((day: any) => (
        <li key={day.id}>
          <Link to={`/wordList/${day.day}`}>DAY {day.day}</Link>
        </li>
      ))}
    </ul>
  );
}

// vue2-default/src/views/DayList.vue
<template>
  <LoadingSpinner v-if="isLoading" />

  <ul v-else class="days" id="days">
    <li v-for="(item, index) in days" :key="index">
      <router-link :to="`/wordList/${index + 1}`">
        DAY {{ item.day }}
      </router-link>
    </li>
  </ul>
</template>

<script>
import LoadingSpinner from '@/components/LoadingSpinner.vue';

export default {
  name: 'DayList',
  components: {
    LoadingSpinner,
  },
  data() {
    return {
      isLoading: true,
      url: this.$store.state.url,
      days: [],
    };
  },
  mounted() {
    this.getDays();
  },
  methods: {
    getDays() {
      this.isLoading = true;
      this.$axios.get(`${this.url}/days`).then((res) => {
        if (res.status === 200) {
          this.days = res.data;
          this.isLoading = false;
        }
      });
    },
  },
};
</script>

<style scoped>
.days {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
}

.days li {
  flex: 20% 0 0;
  box-sizing: border-box;
  padding: 10px;
}

.days a {
  display: block;
  padding: 20px 0;
  font-weight: bold;
  color: #fff;
  text-align: center;
  border-radius: 10px;
  background-color: #353535;
}

.days a:hover {
  background-color: #284b63;
}
</style>
