// vue2-default/src/views/CreateWord.vue
<template>
  <LoadingSpinner v-if="isLoading" />

  <form v-else @submit.prevent>
    <div class="inputWrap">
      <label for="eng">Eng</label>
      <input type="text" id="eng" placeholder="Moon" v-model="eng" />
    </div>
    <div class="inputWrap">
      <label for="kor">Kor</label>
      <input type="text" id="kor" placeholder="달" v-model="kor" />
    </div>
    <div class="inputWrap">
      <label for="dayCount">Day</label>
      <select id="dayCount" v-model="day">
        <option v-for="item in days" :key="item.day" :value="item.day">
          {{ item.day }}
        </option>
      </select>
    </div>
    <div class="inputWrap">
      <button type="button" class="btnCreate" @click="createWord">
        단어 추가
      </button>
    </div>
  </form>
</template>

<script>
import LoadingSpinner from '@/components/LoadingSpinner.vue';

export default {
  name: 'CreateWord',
  components: {
    LoadingSpinner,
  },
  data() {
    return {
      isLoading: true,
      url: this.$store.state.url,
      days: [],
      word: {},
      eng: '',
      kor: '',
      day: 1,
    };
  },
  mounted() {
    this.getDays();
  },
  methods: {
    getDays() {
      this.isLoading = true;
      this.$axios.get(`${this.url}/days`).then((res) => {
        if (res.status === 200) {
          if (res.data.length === 0) {
            alert('등록된 날짜가 없습니다.');
            this.$router.push({ path: `/createDay` });
          } else {
            this.days = res.data;
            this.day = this.days[this.days.length - 1].day;
            this.isLoading = false;
          }
        }
      });
    },
    createWord() {
      let word = {
        day: this.day,
        eng: this.eng.trim(),
        kor: this.kor.trim(),
        isComplete: false,
      };

      if (word.eng === '' || word.kor === '') {
        alert('단어를 입력해주세요.');
      } else {
        this.isLoading = true;
        this.$axios.post(`${this.url}/words`, word).then((res) => {
          if (res.status === 201) {
            alert('단어가 추가되었습니다.');
            this.isLoading = false;
            this.$router.push({ path: `/wordList/${this.day}` });
          }
        });
      }
    },
  },
};
</script>

<style scoped>
.inputWrap {
  padding: 15px 0;
  font-size: 0;
}

.inputWrap label {
  display: inline-block;
  width: 80px;
  font-size: 20px;
  line-height: 40px;
  vertical-align: top;
  border-bottom: 2px solid #d9d9d9;
}

.inputWrap input,
.inputWrap select {
  width: 400px;
  height: 40px;
  font-size: 20px;
  line-height: 40px;
  padding: 0 30px;
  border: none;
  border-bottom: 2px solid #d9d9d9;
  outline: none;
  box-sizing: content-box;
}

.inputWrap input:focus {
  border-bottom: 2px solid #353535;
}
</style>

// react-ts/src/pages/CreateWord.tsx
import axios from 'axios';
import { useRef, useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import LoadingSpinner from '../components/LoadingSpinner';

import '../styles/CreateWord.scoped.css';

export default function CreateWord() {
  const [isLoading, setIsLoading] = useState(false);
  const [days, setData] = useState([]);
  const [day, setDay] = useState(1);

  const url = `http://localhost:5000`;

  const navigate = useNavigate();

  const getDays = useCallback(async () => {
    setIsLoading(true);
    axios.get(`${url}/days`).then((res) => {
      if (res.data.length === 0) {
        alert('등록된 날짜가 없습니다.');
        navigate(`/createDay`);
      } else {
        setData(res.data);
        setDay(res.data.length);
        setIsLoading(false);
      }
    });
  }, [url, navigate]);

  useEffect(() => {
    getDays();
  }, [getDays]);

  function onChange(e: any) {
    e.preventDefault();

    dayRef.current.value = e.target.value;
    setDay(e.target.value);
  }

  function createWord(e: any) {
    e.preventDefault();

    if (!isLoading) {
      const word = {
        day: dayRef.current.value,
        eng: engRef.current.value.trim(),
        kor: korRef.current.value.trim(),
        isComplete: false,
      };

      if (word.eng === '' || word.kor === '') {
        alert('단어를 입력해주세요.');
      } else {
        setIsLoading(true);
        axios.post(`${url}/words`, word).then((res) => {
          if (res.status === 201) {
            alert('단어가 추가되었습니다.');
            setIsLoading(false);
            navigate(`/wordList/${word.day}`);
          }
        });
      }
    }
  }

  const engRef = useRef<any>(null);
  const korRef = useRef<any>(null);
  const dayRef = useRef<any>(null);

  if (isLoading) {
    return <LoadingSpinner />;
  }

  return (
    <form onSubmit={createWord}>
      <div className="inputWrap">
        <label htmlFor="eng">Eng</label>
        <input type="text" id="eng" placeholder="English" ref={engRef} />
      </div>
      <div className="inputWrap">
        <label htmlFor="kor">Kor</label>
        <input type="text" id="kor" placeholder="영어" ref={korRef} />
      </div>
      <div className="inputWrap">
        <label htmlFor="day">Day</label>
        <select id="day" ref={dayRef} value={day} onChange={onChange}>
          {days.map((day: any) => (
            <option key={day.id} value={day.day}>
              {day.day}
            </option>
          ))}
        </select>
      </div>
      <div className="inputWrap">
        <button
          type="submit"
          className={`btnCreate${isLoading ? 'disabled' : ''}`}
        >
          단어 추가
        </button>
      </div>
    </form>
  );
}
